### PR TITLE
Add quick-and-dirty markdown to html rendering

### PR DESCRIPTION
**Pull request by danmactough**
Two parts:
1. Plain old HTML
2. Render the README markdown to HTML body and insert it into the HTML template
## To build

`npm run build`

or to build and open the result in your browser in one step (Mac only)

`npm run view`

### CODE REVIEW

**Comment by cpolitano** [comment]
This works really well except all the special characters turn out all messed up in the html.

**Comment by danmactough** [comment]
@cpolitano Can you post a screenshot of what you're seeing? It looks ok to me.

**Comment by cpolitano** [comment]
codeofconduct

**Comment by danmactough** [comment]
Oh, wow. Thanks, @cpolitano. Let me see why I'm not seeing it that way...

image

**Comment by danmactough** [comment]
@cpolitano I was super sloppy with this -- didn't add a charset 5cacdb8

Can you pull and review again?

**Comment by cpolitano** [comment]
looks perfect now :+1:

**Comment by danmactough** [comment]
phew! 🎉

**Pull request merged**
